path:
  ckpt_path: "./output/ckpt/"
  log_path: "./output/log/"
  exp_name: "test_contrastive"
optimizer:
  batch_size: 12
  betas: [0.9, 0.999]
  eps: 0.000000001
  weight_decay: 0.0
  lr: 0.00005
step:
  max_epochs: 10
  warmup_ratio: 0.2
  num_cycle: 1
trainer:
  grad_clip_thresh: 1.0
  grad_acc: 1
model:
  n_head: 16
  dropout_p: 0.3
  using_contra: True
  using_cma: True
  contra_loss_weight: 0.3
  label_name: 'emotion'
  text_encoder: "klue/roberta-base"
  audio_processor: "w11wo/wav2vec2-xls-r-300m-korean"
  using_model: 'audio'