path:
  ckpt_path: "./output/ckpt/"
  log_path: "./output/log/"
  exp_name: "test_contrastive"
optimizer:
  batch_size: 8
  betas: [0.9, 0.98]
  eps: 0.000000001
  weight_decay: 0.0
  lr: 0.00005
step:
  total_step: 30000
  warm_up_step: 3000
  save_step: 3000
  num_cycle: 2
trainer:
  grad_clip_thresh: 1.0
  grad_acc: 1
model:
  label_name: 'emotion'
  text_encoder: "klue/roberta-base"
  audio_processor: "w11wo/wav2vec2-xls-r-300m-korean"